[tool.poetry]
name = "runekit"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
license = "GPL"

[tool.poetry.dependencies]
python = "^3.9,<3.10"
requests = "^2.25.1"
PySide2 = "^5.15.2"
Pillow = "^8.1.0"
python-xlib = "^0.29"
Cython = "^0.29.21"
click = "^7.1.2"
pymitter = "^0.3.0"
qtutils = "^3.0.0"

[tool.poetry.dev-dependencies]
black = "^20.8b1"

[tool.poetry.build]
script = "build.py"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
